<?php

// autoload_files.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'df3dde27d93d7746e6f3cdd66fd0c97a' => $vendorDir . '/codelicious/php-coda-parser/src/Helpers.php',
);
