<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Codelicious\\Coda\\' => array($vendorDir . '/codelicious/php-coda-parser/src'),
);
