<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit72188faddc1335a27ab7382a4ffb0ac1
{
    public static $files = array (
        'df3dde27d93d7746e6f3cdd66fd0c97a' => __DIR__ . '/..' . '/codelicious/php-coda-parser/src/Helpers.php',
    );

    public static $prefixLengthsPsr4 = array (
        'C' => 
        array (
            'Codelicious\\Coda\\' => 17,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Codelicious\\Coda\\' => 
        array (
            0 => __DIR__ . '/..' . '/codelicious/php-coda-parser/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit72188faddc1335a27ab7382a4ffb0ac1::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit72188faddc1335a27ab7382a4ffb0ac1::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit72188faddc1335a27ab7382a4ffb0ac1::$classMap;

        }, null, ClassLoader::class);
    }
}
